const carSchemaDefinition = {
  sourceSite: { type: String, default: "carsensor" },
  sourceId: { type: String, required: true, unique: true, index: true },
  sourceUrl: { type: String, required: true },
  title: { type: String, default: "" },
  brand: { type: String, default: "", index: true },
  model: { type: String, default: "", index: true },
  year: { type: Number, default: null, index: true },
  mileage: { type: Number, default: null, index: true },
  price: { type: Number, default: null, index: true },
  priceTotal: { type: Number, default: null },
  extraCosts: { type: Number, default: null },
  priceRub: { type: Number, default: null, index: true },
  priceTotalRub: { type: Number, default: null },
  extraCostsRub: { type: Number, default: null },
  currency: { type: String, default: "JPY" },
  region: { type: String, default: "" },
  color: { type: String, default: "" },
  transmission: { type: String, default: "" },
  fuel: { type: String, default: "" },
  engineVolume: { type: String, default: "" },
  bodyType: { type: String, default: "" },
  drive: { type: String, default: "" },
  steering: { type: String, default: "" },
  doors: { type: String, default: "" },
  seats: { type: String, default: "" },
  inspection: { type: String, default: "" },
  repairHistory: { type: String, default: "" },
  oneOwner: { type: String, default: "" },
  nonSmoking: { type: String, default: "" },
  seller: { type: String, default: "" },
  dealerPhone: { type: String, default: "" },
  sellerAddress: { type: String, default: "" },
  vinTail: { type: String, default: "" },
  warranty: { type: String, default: "" },
  service: { type: String, default: "" },
  imageUrls: { type: [String], default: [] },
  features: { type: [String], default: [] },
  description: { type: String, default: "" },
  rawSpecs: { type: Object, default: {} },
  scrapedAt: { type: Date, default: Date.now },
  lastSeenAt: { type: Date, default: Date.now }
};

module.exports = { carSchemaDefinition };
